#! /bin/bash

# TekBASE - Server Control Panel
# Copyright since 2005 by TekLab
# Christian Frankenstein
# Website: www.teklab.de
#          www.teklab.us

VAR_A=$3

if screen -list | grep -q "server$VAR_A-X"; then
    screen -p 0 -S server$VAR_A-X -X stuff $'\003'
fi

exit 0
