#! /bin/bash

# TekBASE - Server Control Panel
# Copyright since 2005 by TekLab
# Christian Frankenstein
# Website: www.teklab.de
#          www.teklab.us

VAR_A=$3

if screen -list | grep -q "server$VAR_A-X"; then
    screen -p 0 -S server$VAR_A-X -X eval 'stuff "say SERVER shuts down in 10 seconds.\015"'
    screen -p 0 -S server$VAR_A-X -X eval 'stuff "save-all\015"'
    sleep 10
    screen -p 0 -S server$VAR_A-X -X eval 'stuff "stop\015"'
fi

exit 0
